### ISSUE TITLE
[EPIC] New linter functions for rhino

### ISSUE THREAD

**Issue by radbasa** [Appsilon/rhino#525]
### Motivation

We want to promote better coding practices.

### Feature description

- [ ] Function line count linter
- [ ] R6 method line count linter
- [ ] Shiny reactive functions line count linter
- [ ] Box module declaration linter
- [ ] Box module usage linter
